<?php

/**
 * @file
 * Main module file.
 */

use Drupal\commerce_currency_resolver_shipping\Plugin\Commerce\ShippingMethod\FlatRateCurrency;
use Drupal\commerce_currency_resolver_shipping\Plugin\Commerce\ShippingMethod\FlatRatePerItemCurrency;

/**
 * Implements hook_commerce_shipping_method_info_alter().
 */
function commerce_currency_resolver_shipping_commerce_shipping_method_info_alter(array &$definitions) {
  $definitions['flat_rate_per_item']['class'] = FlatRatePerItemCurrency::class;
  $definitions['flat_rate']['class'] = FlatRateCurrency::class;
}
