commerce_currency_resolver.settings:
  type: config_object
  label: 'Commerce currency resolver settings'
  mapping:
    currency_source:
      type: string
      label: 'Currency source'
    currency_field_prefix:
      type: string
      label: 'Currency field prefix'
    currency_exchange_rates:
      type: string
      label: 'Exchange rates service'
