<?php

/**
 * @file
 * Main module file.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_view_alter().
 */
function commerce_currency_resolver_cookie_entity_view_alter(array &$build, EntityInterface $entity, $view_mode): void {
  // Add our cache context.
  if (isset($build['#commerce_product']) || isset($build['#commerce_product_variation'])) {
    $build['#cache']['contexts'][] = 'currency_resolver';
  }
}
