commerce_currency_resolver_language.currency_mapping:
  type: config_object
  label: 'Currency language mapping'
  mapping:
    matrix:
      type: sequence
      label: 'Matrix'
      sequence:
        type: string
